// Balance values live here; labels/ranges also generate the in-game tuning editor.
const value=(value:number,label:string,group:string,min:number,max:number,step=.1,note='Applies live.')=>({value,label,group,min,max,step,note});
export const tuningSpec={
 mineSeconds:value(2.8,'Excavate dirt · seconds','Mining & work',.1,120),
 rockSeconds:value(4,'Excavate rock · seconds','Mining & work',.1,120),
 goldSeconds:value(.5,'Gold extraction interval · seconds','Mining & work',.05,30,.05),
 goldYield:value(15,'Gold per extraction','Mining & work',1,1000,1),
 gemSeconds:value(.5,'Gem extraction interval · seconds','Mining & work',.05,30,.05),
 gemYield:value(15,'Gold per gem extraction','Mining & work',1,1000,1),
 minersPerResourceWorker:value(3,'Miners per resource worker','Mining & work',1,30,1,'Reserve about one resource worker per this many available miners, with a minimum of one when marked gold or gems are reachable.'),
 minerAssignmentSeconds:value(20,'Miner assignment duration · work seconds','Mining & work',1,120,1,'Keep the same kind of work for this much productive time. Travel and delivery do not consume a resource assignment; finish the current task before rebalancing.'),
 carry:value(45,'Bag capacity · gold','Mining & work',1,1000,1,'Applies to new loads; existing bags are preserved.'),
 claimSeconds:value(.5,'Claim floor · seconds','Mining & work',.1,60),
 reinforceSeconds:value(6,'Reinforce wall · seconds','Mining & work',.1,180),
 wallBuildSeconds:value(24,'Build wall · seconds','Mining & work',1,600,1,'Must exceed rock/dirt excavation plus reinforcement.'),
 trainingInterval:value(45,'Cooldown after gaining a training level · seconds','Training & research',1,600,1),
 combatExperienceRate:value(2,'Combat experience · training rate multiplier','Training & research',0,10,.1,'Successful melee hits grant this many XP per base attack-interval second. Training grants 1 XP per second; Haste speeds both.'),
 recruitmentSeconds:value(45,'Specialist arrival interval · seconds','Economy & world',1,600,1,'One eligible arrival per interval; requires spare service, bed and food capacity.'),
 minerMinimumCost:value(50,'Miner base recruitment cost · gold','Economy & world',0,10000,1,'Next price adds the cost step for each living Miner, including the starting crew.'),
 minerCostStep:value(25,'Recruitment cost per living Miner · gold','Economy & world',1,10000,1),
 paydaySeconds:value(120,'Shared payday interval · seconds','Economy & world',1,3600,1,'Used when scheduling the next payday; existing due amounts and dates are retained.'),
 wageCollectionSeconds:value(1,'Collect wages · seconds','Economy & world',.1,60,.1,'Gold is deducted only after a physical treasury visit.'),
 wageGraceSeconds:value(45,'Overdue wage warning after · seconds','Economy & world',0,600,1,'Allows ordinary travel and queues before wage dissatisfaction starts.'),
 moraleGraceSeconds:value(120,'Shortage grace · seconds','Needs & food',1,1800,1,'Continuous unmet support before a warning.'),
 moraleDepartureSeconds:value(180,'Leave after warning · seconds','Needs & food',1,1800,1,'Additional unresolved time before walking to the Hearth.'),
 moraleRecoveryRate:value(2,'Shortage recovery · seconds/second','Needs & food',.1,20,.1),
 hearthHealth:value(400,'Starting Hearth health','Economy & world',1,10000,1,'New stronghold only.'),
 hearthActivationSeconds:value(8,'Onward Hearth activation · seconds','Economy & world',1,120,1),
 hearthThreatRadius:value(4,'Onward Hearth enemy exclusion · tiles','Economy & world',1,12,1),
 speed:value(1.8,'Walking speed · tiles/second','Movement',.1,10),
 radius:value(.17,'Terrain collision radius · tiles','Movement',.05,.24,.01),
 avoidanceRadius:value(.55,'Dwarf avoidance radius · tiles','Movement',0,1,.05),
 avoidanceStrength:value(.8,'Dwarf avoidance strength','Movement',0,2,.1),
 arrivalDistance:value(.055,'Waypoint arrival distance','Movement',.01,.1,.005),
 stallSeconds:value(1.5,'Repath after stalling · seconds','Movement',.2,10),
 retrySeconds:value(.8,'Idle work retry · seconds','Movement',.1,5),
 facilityRetry:value(8,'Blocked facility retry · seconds','Movement',1,60,1),
 restInterval:value(100,'Energy depletion · seconds','Needs & food',10,1800,1),
 restSeconds:value(6,'Full rest duration · seconds','Needs & food',.1,120),
 hungerInterval:value(85,'Hunger depletion · seconds','Needs & food',10,1800,1),
 restThreshold:value(.3,'Seek bed below energy','Needs & food',.05,.95,.05),
 hungerThreshold:value(.3,'Seek meal below hunger','Needs & food',.05,.95,.05),
 eatSeconds:value(4,'Eat meal · seconds','Needs & food',.1,120),
 startingGold:value(400,'Starting gold','Economy & world',0,100000,1,'New stronghold only.'),
 startingMiners:value(3,'Starting miners','Economy & world',1,30,1,'New stronghold only.'),
 seamGold:value(90,'Gold per seam tile','Economy & world',1,10000,1,'New stronghold only.'),
 hearthRoomTiles:value(9,'Hearth storage · Treasure Room squares','Economy & world',1,100,1,'New stronghold only; multiplied by Treasure Room cost.'),
 reclaimRatio:value(.5,'Room reclaim fraction','Economy & world',0,.95,.05,'Fraction of original payment; rounded down per tile.'),
 sightRadius:value(6,'Dwarf sight · tiles','Economy & world',1,20,1,'Applies live; already discovered terrain remains known.'),
 initialSight:value(8,'Starting sight · tiles','Economy & world',1,20,1,'New stronghold only.'),
 claimedRadius:value(7,'Starting claimed radius · tiles','Economy & world',1,20,1,'New stronghold only.'),
 panSpeed:value(.5,'Pan speed relative to zoom','Camera',.05,3,.05),
 orbitSpeed:value(1.2,'Keyboard orbit · radians/second','Camera',.1,5),
 edgePixels:value(18,'Edge scrolling band · pixels','Camera',0,100,1),
 dragSensitivity:value(.006,'Middle drag sensitivity','Camera',.001,.03,.001),
 wheelSensitivity:value(.0015,'Wheel zoom sensitivity','Camera',.0001,.01,.0001),
 minZoom:value(9,'Minimum camera distance','Camera',4,100,1),
 maxZoom:value(58,'Maximum camera distance','Camera',4,100,1),
 homeZoom:value(23,'Home camera distance','Camera',4,100,1),
 initialZoom:value(25,'Initial camera distance','Camera',4,100,1,'New page only.'),
 initialAngle:value(-Math.PI/2.4,'Initial orbit angle · radians','Camera',-6.3,6.3,.01,'New page only.'),
 initialTilt:value(.76,'Camera tilt · radians','Camera',.3,1.2,.01,'New page only.')
};
export type TuningKey=keyof typeof tuningSpec;
export const tuning=Object.fromEntries(Object.entries(tuningSpec).map(([key,s])=>[key,s.value])) as Record<TuningKey,number>;
