// Balance values live here; labels/ranges also generate the in-game tuning editor.
const value=(value:number,label:string,group:string,min:number,max:number,step=.1,note='Applies live.')=>({value,label,group,min,max,step,note});
export const tuningSpec={
 mineSeconds:value(2.8,'Excavate dirt · seconds','Mining & work',.1,120),
 rockSeconds:value(4,'Excavate rock · seconds','Mining & work',.1,120),
 goldSeconds:value(.5,'Gold extraction interval · seconds','Mining & work',.05,30,.05),
 goldYield:value(15,'Gold per extraction','Mining & work',1,1000,1),
 gemSeconds:value(6,'Gem extraction interval · seconds','Mining & work',.1,120),
 gemYield:value(8,'Gold per gem extraction','Mining & work',1,1000,1),
 carry:value(45,'Bag capacity · gold','Mining & work',1,1000,1,'Applies to new loads; existing bags are preserved.'),
 claimSeconds:value(.5,'Claim floor · seconds','Mining & work',.1,60),
 reinforceSeconds:value(6,'Reinforce wall · seconds','Mining & work',.1,180),
 wallBuildSeconds:value(24,'Build wall · seconds','Mining & work',1,600,1,'Must exceed rock/dirt excavation plus reinforcement.'),
 trainingSeconds:value(12,'Training per level · seconds','Training & research',.1,180),
 trainingInterval:value(45,'Cooldown after gaining a training level · seconds','Training & research',1,600,1),
 trainingLevels:value(5,'Maximum training level','Training & research',1,20,1),
 trainingBonus:value(.08,'Work speed gain per training level','Training & research',0,.5,.01),
 recruitmentSeconds:value(45,'Specialist arrival interval · seconds','Economy & world',1,600,1,'One eligible arrival per interval; requires spare service, bed and food capacity.'),
 speed:value(1.8,'Walking speed · tiles/second','Movement',.1,10),
 radius:value(.17,'Terrain collision radius · tiles','Movement',.05,.24,.01),
 avoidanceRadius:value(.55,'Dwarf avoidance radius · tiles','Movement',0,1,.05),
 avoidanceStrength:value(.8,'Dwarf avoidance strength','Movement',0,2,.1),
 arrivalDistance:value(.055,'Waypoint arrival distance','Movement',.01,.1,.005),
 stallSeconds:value(1.5,'Repath after stalling · seconds','Movement',.2,10),
 retrySeconds:value(.8,'Idle work retry · seconds','Movement',.1,5),
 facilityRetry:value(8,'Blocked facility retry · seconds','Movement',1,60,1),
 restInterval:value(100,'Energy depletion · seconds','Needs & food',10,1800,1),
 restSeconds:value(6,'Full rest duration · seconds','Needs & food',.1,120),
 hungerInterval:value(85,'Hunger depletion · seconds','Needs & food',10,1800,1),
 restThreshold:value(.3,'Seek bed below energy','Needs & food',.05,.95,.05),
 hungerThreshold:value(.3,'Seek meal below hunger','Needs & food',.05,.95,.05),
 eatSeconds:value(4,'Eat meal · seconds','Needs & food',.1,120),
 startingGold:value(400,'Starting gold','Economy & world',0,100000,1,'New stronghold only.'),
 startingMiners:value(3,'Starting miners','Economy & world',1,30,1,'New stronghold only.'),
 seamGold:value(90,'Gold per seam tile','Economy & world',1,10000,1,'New stronghold only.'),
 hearthRoomTiles:value(9,'Hearth storage · Treasure Room squares','Economy & world',1,100,1,'New stronghold only; multiplied by Treasure Room cost.'),
 reclaimRatio:value(.5,'Room reclaim fraction','Economy & world',0,.95,.05,'Fraction of original payment; rounded down per tile.'),
 sightRadius:value(6,'Dwarf sight · tiles','Economy & world',1,20,1,'Applies live; already discovered terrain remains known.'),
 initialSight:value(8,'Starting sight · tiles','Economy & world',1,20,1,'New stronghold only.'),
 claimedRadius:value(7,'Starting claimed radius · tiles','Economy & world',1,20,1,'New stronghold only.'),
 panSpeed:value(.5,'Pan speed relative to zoom','Camera',.05,3,.05),
 orbitSpeed:value(1.2,'Keyboard orbit · radians/second','Camera',.1,5),
 edgePixels:value(18,'Edge scrolling band · pixels','Camera',0,100,1),
 dragSensitivity:value(.006,'Middle drag sensitivity','Camera',.001,.03,.001),
 wheelSensitivity:value(.0015,'Wheel zoom sensitivity','Camera',.0001,.01,.0001),
 minZoom:value(9,'Minimum camera distance','Camera',4,100,1),
 maxZoom:value(58,'Maximum camera distance','Camera',4,100,1),
 homeZoom:value(23,'Home camera distance','Camera',4,100,1),
 initialZoom:value(25,'Initial camera distance','Camera',4,100,1,'New page only.'),
 initialAngle:value(-Math.PI/2.4,'Initial orbit angle · radians','Camera',-6.3,6.3,.01,'New page only.'),
 initialTilt:value(.76,'Camera tilt · radians','Camera',.3,1.2,.01,'New page only.')
};
export type TuningKey=keyof typeof tuningSpec;
export const tuning=Object.fromEntries(Object.entries(tuningSpec).map(([key,s])=>[key,s.value])) as Record<TuningKey,number>;
