import './style.css';
import { prototypeLevel } from './content/levels';
import { createWorld } from './game/world';
import { GameScene } from './view/scene';
import { CameraControls } from './view/controls';
import { Sidebar } from './ui/sidebar';
import {addMiners,tick} from './game/simulation';
import {ResidentView} from './view/residents';
import {Selection} from './ui/selection';
const world=createWorld(prototypeLevel);
addMiners(world);
const view=new GameScene(document.querySelector<HTMLCanvasElement>('#world')!,world);
const controls=new CameraControls(view);
const selection=new Selection(view);
const sidebar=new Sidebar(view,controls,selection);
const residents=new ResidentView(view);
let uiTime=0;
view.engine.runRenderLoop(()=>{const dt=Math.min(.05,view.engine.getDeltaTime()/1000);controls.update(dt);tick(world,dt);residents.update();view.render();uiTime+=dt;if(uiTime>.15){sidebar.update();uiTime=0;}});
