import './style.css';
import { prototypeLevel } from './content/levels';
import { createWorld } from './game/world';
import { GameScene } from './view/scene';
import { CameraControls } from './view/controls';
import { Sidebar } from './ui/sidebar';
const world=createWorld(prototypeLevel);
const view=new GameScene(document.querySelector<HTMLCanvasElement>('#world')!,world);
const controls=new CameraControls(view);
const sidebar=new Sidebar(view,controls);
let uiTime=0;
view.engine.runRenderLoop(()=>{const dt=Math.min(.05,view.engine.getDeltaTime()/1000);controls.update(dt);view.render();uiTime+=dt;if(uiTime>.15){sidebar.update();uiTime=0;}});
